services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: app-next
    environment:
      DEVELOPMENT_MODE: ${DEVELOPMENT_MODE}
    ports:
      - "3030:3030"
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - db

  db:
    container_name: db-next
    image: "postgres:16.0-alpine3.18"
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT-5432}:5432"
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network: # Define uma rede bridge personalizada
    driver: bridge
