services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: app-next
    environment:
      DEVELOPMENT_MODE: ${DEVELOPMENT_MODE}
    ports:
      - "3030:3030"
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
